import {
    interpolateBrBG,
    interpolatePRGn,
    interpolatePiYG,
    interpolatePuOr,
    interpolateRdBu,
    interpolateRdGy,
    interpolateRdYlBu,
    interpolateRdYlGn,
    interpolateSpectral,
    interpolateBlues,
    interpolateGreens,
    interpolateGreys,
    interpolateOranges,
    interpolatePurples,
    interpolateReds,
    interpolateTurbo,
    interpolateViridis,
    interpolateInferno,
    interpolateMagma,
    interpolatePlasma,
    interpolateCividis,
    interpolateWarm,
    interpolateCool,
    interpolateCubehelixDefault,
    interpolateBuGn,
    interpolateBuPu,
    interpolateGnBu,
    interpolateOrRd,
    interpolatePuBuGn,
    interpolatePuBu,
    interpolatePuRd,
    interpolateRdPu,
    interpolateYlGnBu,
    interpolateYlGn,
    interpolateYlOrBr,
    interpolateYlOrRd,
    interpolateRainbow,
    interpolateSinebow,
} from 'd3';

import i18n from '@/i18n';

export default {
    base: process.env.VUE_APP_BASE,
    title: process.env.VUE_APP_TITLE,
    url: process.env.VUE_APP_URL,
    version: process.env.VUE_APP_VERSION,
    links: {
        buymeacoffee: 'https://www.buymeacoffee.com/niekes',
    },
    shapes: {
        rect: {
            amount: 16,
            bgColor: '#000000',
            borderRadius: {
                tl: 0, tr: 0, bl: 0, br: 0,
            },
            colorInterPolator: null,
            cx: 0,
            cy: 0,
            distance: 16,
            height: 256,
            calcOpacity: [],
            calcOpacityOptions: [
                {
                    value: 'interpolate',
                    text: i18n.t('home.interpolateOpacity'),
                },
                {
                    value: 'flip',
                    text: i18n.t('home.flip'),
                },
            ],
            flipColorInterpolator: false,
            flipColorInterpolatorOptions: [
                {
                    value: true,
                    text: i18n.t('home.flipColorScheme'),
                },
            ],
            rotation: 0,
            stroke: true,
            strokeOptions: [
                {
                    value: true,
                    text: i18n.t('home.stroke'),
                },
                {
                    value: false,
                    text: i18n.t('home.fill'),
                },
            ],
            strokeWidth: 1,
            calcStrokeWidth: [],
            calcStrokeWidthOptions: [
                {
                    value: 'interpolate',
                    text: i18n.t('home.interpolateStrokeWidth'),
                },
                {
                    value: 'flip',
                    text: i18n.t('home.flip'),
                },
            ],
            width: 256,
            borderRadiusIsLocked: true,
            sizeIsLocked: true,

        },
        circle: {
            amount: 16,
            bgColor: '#000000',
            colorInterPolator: null,
            cx: 0,
            cy: 0,
            distance: 16,
            flipColorInterpolator: false,
            flipColorInterpolatorOptions: [
                {
                    value: true,
                    text: i18n.t('home.flipColorScheme'),
                },
            ],
            strokeWidth: 1,
            calcStrokeWidth: [],
            calcStrokeWidthOptions: [
                {
                    value: 'interpolate',
                    text: i18n.t('home.interpolateStrokeWidth'),
                },
                {
                    value: 'flip',
                    text: i18n.t('home.flip'),
                },
            ],
            calcOpacity: [],
            calcOpacityOptions: [
                {
                    value: 'interpolate',
                    text: i18n.t('home.interpolateOpacity'),
                },
                {
                    value: 'flip',
                    text: i18n.t('home.flip'),
                },
            ],
            radiusX: 256,
            radiusY: 256,
            rotation: 0,
            stroke: true,
            strokeOptions: [
                {
                    value: true,
                    text: i18n.t('home.stroke'),
                },
                {
                    value: false,
                    text: i18n.t('home.fill'),
                },
            ],
            startAngle: 0,
            endAngle: 360,
            radiusIsLocked: true,
        },
        polygon: {
            amount: 16,
            bgColor: '#000000',
            borderRadius: 0,
            colorInterPolator: null,
            cx: 0,
            cy: 0,
            distance: 16,
            flipColorInterpolator: false,
            flipColorInterpolatorOptions: [
                {
                    value: true,
                    text: i18n.t('home.flipColorScheme'),
                },
            ],
            strokeWidth: 1,
            calcStrokeWidth: [],
            calcStrokeWidthOptions: [
                {
                    value: 'interpolate',
                    text: i18n.t('home.interpolateStrokeWidth'),
                },
                {
                    value: 'flip',
                    text: i18n.t('home.flip'),
                },
            ],
            calcOpacity: [],
            calcOpacityOptions: [
                {
                    value: 'interpolate',
                    text: i18n.t('home.interpolateOpacity'),
                },
                {
                    value: 'flip',
                    text: i18n.t('home.flip'),
                },
            ],
            rotation: 0,
            sides: 5,
            size: 256,
            stroke: true,
            strokeOptions: [
                {
                    value: true,
                    text: i18n.t('home.stroke'),
                },
                {
                    value: false,
                    text: i18n.t('home.fill'),
                },
            ],
        },
    },
    format: {
        float: '.2~f',
        standard: '.4~s',
        currency: '$.3~s',
        percent: '.1~%',
    },
    colorInterPolators: [
        { name: 'interpolateBrBG', fn: interpolateBrBG },
        { name: 'interpolatePRGn', fn: interpolatePRGn },
        { name: 'interpolatePiYG', fn: interpolatePiYG },
        { name: 'interpolatePuOr', fn: interpolatePuOr },
        { name: 'interpolateRdBu', fn: interpolateRdBu },
        { name: 'interpolateRdGy', fn: interpolateRdGy },
        { name: 'interpolateRdYlBu', fn: interpolateRdYlBu },
        { name: 'interpolateRdYlGn', fn: interpolateRdYlGn },
        { name: 'interpolateSpectral', fn: interpolateSpectral },
        { name: 'interpolateBlues', fn: interpolateBlues },
        { name: 'interpolateGreens', fn: interpolateGreens },
        { name: 'interpolateGreys', fn: interpolateGreys },
        { name: 'interpolateOranges', fn: interpolateOranges },
        { name: 'interpolatePurples', fn: interpolatePurples },
        { name: 'interpolateReds', fn: interpolateReds },
        { name: 'interpolateTurbo', fn: interpolateTurbo },
        { name: 'interpolateViridis', fn: interpolateViridis },
        { name: 'interpolateInferno', fn: interpolateInferno },
        { name: 'interpolateMagma', fn: interpolateMagma },
        { name: 'interpolatePlasma', fn: interpolatePlasma },
        { name: 'interpolateCividis', fn: interpolateCividis },
        { name: 'interpolateWarm', fn: interpolateWarm },
        { name: 'interpolateCool', fn: interpolateCool },
        { name: 'interpolateCubehelixDefault', fn: interpolateCubehelixDefault },
        { name: 'interpolateBuGn', fn: interpolateBuGn },
        { name: 'interpolateBuPu', fn: interpolateBuPu },
        { name: 'interpolateGnBu', fn: interpolateGnBu },
        { name: 'interpolateOrRd', fn: interpolateOrRd },
        { name: 'interpolatePuBuGn', fn: interpolatePuBuGn },
        { name: 'interpolatePuBu', fn: interpolatePuBu },
        { name: 'interpolatePuRd', fn: interpolatePuRd },
        { name: 'interpolateRdPu', fn: interpolateRdPu },
        { name: 'interpolateYlGnBu', fn: interpolateYlGnBu },
        { name: 'interpolateYlGn', fn: interpolateYlGn },
        { name: 'interpolateYlOrBr', fn: interpolateYlOrBr },
        { name: 'interpolateYlOrRd', fn: interpolateYlOrRd },
        { name: 'interpolateRainbow', fn: interpolateRainbow },
        { name: 'interpolateSinebow', fn: interpolateSinebow },
    ],
};
