import {
    interpolateBrBG,
    interpolatePRGn,
    interpolatePiYG,
    interpolatePuOr,
    interpolateRdBu,
    interpolateRdGy,
    interpolateRdYlBu,
    interpolateRdYlGn,
    interpolateSpectral,
    interpolateBlues,
    interpolateGreens,
    interpolateGreys,
    interpolateOranges,
    interpolatePurples,
    interpolateReds,
    interpolateTurbo,
    interpolateViridis,
    interpolateInferno,
    interpolateMagma,
    interpolatePlasma,
    interpolateCividis,
    interpolateWarm,
    interpolateCool,
    interpolateCubehelixDefault,
    interpolateBuGn,
    interpolateBuPu,
    interpolateGnBu,
    interpolateOrRd,
    interpolatePuBuGn,
    interpolatePuBu,
    interpolatePuRd,
    interpolateRdPu,
    interpolateYlGnBu,
    interpolateYlGn,
    interpolateYlOrBr,
    interpolateYlOrRd,
    interpolateRainbow,
    interpolateSinebow,
} from 'd3';

export default {
    base: process.env.VUE_APP_BASE,
    title: process.env.VUE_APP_TITLE,
    url: process.env.VUE_APP_URL,
    version: process.env.VUE_APP_VERSION,
    links: {
        buymeacoffee: 'https://www.buymeacoffee.com/niekes',
    },
    colorInterPolators: [
        { name: 'interpolateBrBG', fn: interpolateBrBG },
        { name: 'interpolatePRGn', fn: interpolatePRGn },
        { name: 'interpolatePiYG', fn: interpolatePiYG },
        { name: 'interpolatePuOr', fn: interpolatePuOr },
        { name: 'interpolateRdBu', fn: interpolateRdBu },
        { name: 'interpolateRdGy', fn: interpolateRdGy },
        { name: 'interpolateRdYlBu', fn: interpolateRdYlBu },
        { name: 'interpolateRdYlGn', fn: interpolateRdYlGn },
        { name: 'interpolateSpectral', fn: interpolateSpectral },
        { name: 'interpolateBlues', fn: interpolateBlues },
        { name: 'interpolateGreens', fn: interpolateGreens },
        { name: 'interpolateGreys', fn: interpolateGreys },
        { name: 'interpolateOranges', fn: interpolateOranges },
        { name: 'interpolatePurples', fn: interpolatePurples },
        { name: 'interpolateReds', fn: interpolateReds },
        { name: 'interpolateTurbo', fn: interpolateTurbo },
        { name: 'interpolateViridis', fn: interpolateViridis },
        { name: 'interpolateInferno', fn: interpolateInferno },
        { name: 'interpolateMagma', fn: interpolateMagma },
        { name: 'interpolatePlasma', fn: interpolatePlasma },
        { name: 'interpolateCividis', fn: interpolateCividis },
        { name: 'interpolateWarm', fn: interpolateWarm },
        { name: 'interpolateCool', fn: interpolateCool },
        { name: 'interpolateCubehelixDefault', fn: interpolateCubehelixDefault },
        { name: 'interpolateBuGn', fn: interpolateBuGn },
        { name: 'interpolateBuPu', fn: interpolateBuPu },
        { name: 'interpolateGnBu', fn: interpolateGnBu },
        { name: 'interpolateOrRd', fn: interpolateOrRd },
        { name: 'interpolatePuBuGn', fn: interpolatePuBuGn },
        { name: 'interpolatePuBu', fn: interpolatePuBu },
        { name: 'interpolatePuRd', fn: interpolatePuRd },
        { name: 'interpolateRdPu', fn: interpolateRdPu },
        { name: 'interpolateYlGnBu', fn: interpolateYlGnBu },
        { name: 'interpolateYlGn', fn: interpolateYlGn },
        { name: 'interpolateYlOrBr', fn: interpolateYlOrBr },
        { name: 'interpolateYlOrRd', fn: interpolateYlOrRd },
        { name: 'interpolateRainbow', fn: interpolateRainbow },
        { name: 'interpolateSinebow', fn: interpolateSinebow },
    ],
};
