import {
    interpolateBrBG,
    interpolatePRGn,
    interpolatePiYG,
    interpolatePuOr,
    interpolateRdBu,
    interpolateRdGy,
    interpolateRdYlBu,
    interpolateRdYlGn,
    interpolateSpectral,
    interpolateBlues,
    interpolateGreens,
    interpolateGreys,
    interpolateOranges,
    interpolatePurples,
    interpolateReds,
    interpolateTurbo,
    interpolateViridis,
    interpolateInferno,
    interpolateMagma,
    interpolatePlasma,
    interpolateCividis,
    interpolateWarm,
    interpolateCool,
    interpolateCubehelixDefault,
    interpolateBuGn,
    interpolateBuPu,
    interpolateGnBu,
    interpolateOrRd,
    interpolatePuBuGn,
    interpolatePuBu,
    interpolatePuRd,
    interpolateRdPu,
    interpolateYlGnBu,
    interpolateYlGn,
    interpolateYlOrBr,
    interpolateYlOrRd,
    interpolateRainbow,
    interpolateSinebow,
} from 'd3';

import {
    parse,
} from 'qs';

import i18n from '@/i18n';

const query = parse(window.location.search.substring(1), { arrayFormat: 'comma' });

const { shape } = query;
const isRect = shape === 'rect';
const isCircle = shape === 'circle';
const isPolygon = shape === 'polygon';

export default {
    base: process.env.VUE_APP_BASE,
    title: process.env.VUE_APP_TITLE,
    url: process.env.VUE_APP_URL,
    version: process.env.VUE_APP_VERSION,
    links: {
        buymeacoffee: 'https://www.buymeacoffee.com/niekes',
    },
    shapes: {
        selected: shape || 'rect',
        rect: {
            amount: (isRect && +query.amount) || 16,
            bgColor: (isRect && query.bgColor) || '#000000',
            borderRadius: {
                tl: (isRect && +query.borderRadius.tl) || 0,
                tr: (isRect && +query.borderRadius.tr) || 0,
                bl: (isRect && +query.borderRadius.bl) || 0,
                br: (isRect && +query.borderRadius.br) || 0,
            },
            colorInterPolator: (isRect && query.colorInterPolator) || 'interpolateBrBG',
            cx: (isRect && +query.cx) || 0,
            cy: (isRect && +query.cy) || 0,
            distance: (isRect && +query.distance) || 16,
            height: (isRect && +query.height) || 256,
            calcOpacity: (isRect && query.calcOpacity.split(',')) || [],
            calcOpacityOptions: [
                {
                    value: 'interpolate',
                    text: i18n.t('home.interpolateOpacity'),
                },
                {
                    value: 'flip',
                    text: i18n.t('home.flip'),
                },
            ],
            flipColorInterpolator: isRect ? JSON.parse(query.flipColorInterpolator) : false,
            flipColorInterpolatorOptions: [
                {
                    value: true,
                    text: i18n.t('home.flipColorScheme'),
                },
            ],
            rotation: (isRect && +query.rotation) || 0,
            stroke: isRect ? JSON.parse(query.stroke) : true,
            strokeOptions: [
                {
                    value: true,
                    text: i18n.t('home.stroke'),
                },
                {
                    value: false,
                    text: i18n.t('home.fill'),
                },
            ],
            strokeWidth: (isRect && +query.strokeWidth) || 3,
            calcStrokeWidth: (isRect && query.calcStrokeWidth.split(',')) || [],
            calcStrokeWidthOptions: [
                {
                    value: 'interpolate',
                    text: i18n.t('home.interpolateStrokeWidth'),
                },
                {
                    value: 'flip',
                    text: i18n.t('home.flip'),
                },
            ],
            width: (isRect && +query.width) || 256,
            borderRadiusIsLocked: isRect ? JSON.parse(query.borderRadiusIsLocked) : true,
            sizeIsLocked: isRect ? JSON.parse(query.sizeIsLocked) : true,

        },
        circle: {
            amount: (isCircle && +query.amount) || 16,
            bgColor: (isCircle && query.bgColor) || '#000000',
            colorInterPolator: (isCircle && query.colorInterPolator) || 'interpolateBrBG',
            cx: (isCircle && +query.cx) || 0,
            cy: (isCircle && +query.cy) || 0,
            distance: (isCircle && +query.distance) || 16,
            flipColorInterpolator: isCircle ? JSON.parse(query.flipColorInterpolator) : false,
            flipColorInterpolatorOptions: [
                {
                    value: true,
                    text: i18n.t('home.flipColorScheme'),
                },
            ],
            strokeWidth: (isCircle && +query.strokeWidth) || 3,
            calcStrokeWidth: (isCircle && query.calcStrokeWidth.split(',')) || [],
            calcStrokeWidthOptions: [
                {
                    value: 'interpolate',
                    text: i18n.t('home.interpolateStrokeWidth'),
                },
                {
                    value: 'flip',
                    text: i18n.t('home.flip'),
                },
            ],
            calcOpacity: (isCircle && query.calcOpacity.split(',')) || [],
            calcOpacityOptions: [
                {
                    value: 'interpolate',
                    text: i18n.t('home.interpolateOpacity'),
                },
                {
                    value: 'flip',
                    text: i18n.t('home.flip'),
                },
            ],
            radiusX: (isCircle && +query.radiusX) || 256,
            radiusY: (isCircle && +query.radiusY) || 256,
            rotation: (isCircle && +query.rotation) || 0,
            stroke: isCircle ? JSON.parse(query.stroke) : true,
            strokeOptions: [
                {
                    value: true,
                    text: i18n.t('home.stroke'),
                },
                {
                    value: false,
                    text: i18n.t('home.fill'),
                },
            ],
            radiusIsLocked: isCircle ? JSON.parse(query.radiusIsLocked) : true,
        },
        polygon: {
            amount: (isPolygon && +query.amount) || 16,
            bgColor: (isPolygon && query.bgColor) || '#000000',
            borderRadius: (isPolygon && +query.borderRadius) || 0,
            colorInterPolator: (isPolygon && query.colorInterPolator) || 'interpolateBrBG',
            cx: (isPolygon && +query.cx) || 0,
            cy: (isPolygon && +query.cy) || 0,
            distance: (isPolygon && +query.distance) || 16,
            flipColorInterpolator: isPolygon ? JSON.parse(query.flipColorInterpolator) : false,
            flipColorInterpolatorOptions: [
                {
                    value: true,
                    text: i18n.t('home.flipColorScheme'),
                },
            ],
            strokeWidth: (isPolygon && +query.strokeWidth) || 3,
            calcStrokeWidth: (isPolygon && query.calcStrokeWidth.split(',')) || [],
            calcStrokeWidthOptions: [
                {
                    value: 'interpolate',
                    text: i18n.t('home.interpolateStrokeWidth'),
                },
                {
                    value: 'flip',
                    text: i18n.t('home.flip'),
                },
            ],
            calcOpacity: (isPolygon && query.calcOpacity.split(',')) || [],
            calcOpacityOptions: [
                {
                    value: 'interpolate',
                    text: i18n.t('home.interpolateOpacity'),
                },
                {
                    value: 'flip',
                    text: i18n.t('home.flip'),
                },
            ],
            rotation: (isPolygon && +query.rotation) || 0,
            sides: (isPolygon && +query.sides) || 5,
            size: (isPolygon && +query.size) || 256,
            stroke: isPolygon ? JSON.parse(query.stroke) : true,
            strokeOptions: [
                {
                    value: true,
                    text: i18n.t('home.stroke'),
                },
                {
                    value: false,
                    text: i18n.t('home.fill'),
                },
            ],
        },
    },
    icons: [
        /* eslint-disable global-require */
        {
            src: require('@/assets/img/icon-0.png'),
            shape: 'circle',
            parameters: {
                amount: 24,
                distance: 5.6,
                radiusX: 400,
                radiusY: 265,
                rotation: 1000,
                strokeWidth: 30,
                calcOpacity: ['interpolate', 'flip'],
                colorInterPolator: 'interpolatePlasma',
                radiusIsLocked: false,
            },
        },
        {
            src: require('@/assets/img/icon-1.png'),
            shape: 'circle',
            parameters: {
                amount: 76,
                distance: 1.8,
                radiusX: 140,
                radiusY: 440,
                rotation: 1333,
                strokeWidth: 16,
                calcOpacity: ['interpolate', 'flip'],
                calcStrokeWidth: ['interpolate', 'flip'],
                colorInterPolator: 'interpolateViridis',
                radiusIsLocked: false,
            },
        },
        {
            src: require('@/assets/img/icon-2.png'),
            shape: 'circle',
            parameters: {
                amount: 33,
                distance: 3.6,
                radiusX: 422,
                radiusY: 265,
                rotation: 937,
                strokeWidth: 30,
                calcOpacity: ['interpolate', 'flip'],
                colorInterPolator: 'interpolateRdPu',
                radiusIsLocked: false,
            },
        },
        {
            src: require('@/assets/img/icon-3.png'),
            shape: 'circle',
            parameters: {
                amount: 173,
                distance: 1,
                radiusX: 162,
                radiusY: 418,
                rotation: -84,
                strokeWidth: 6,
                calcOpacity: ['interpolate', 'flip'],
                colorInterPolator: 'interpolatePlasma',
                radiusIsLocked: false,
                flipColorInterpolator: true,
            },
        },
        {
            src: require('@/assets/img/icon-4.png'),
            shape: 'circle',
            parameters: {
                amount: 116,
                distance: 2.4,
                radiusX: 424,
                radiusY: 386,
                rotation: 246,
                strokeWidth: 3,
                calcOpacity: ['interpolate', 'flip'],
                calcStrokeWidth: ['interpolate', 'flip'],
                colorInterPolator: 'interpolateRainbow',
                radiusIsLocked: false,
                flipColorInterpolator: true,
            },
        },
        {
            src: require('@/assets/img/icon-5.png'),
            shape: 'polygon',
            parameters: {
                amount: 30,
                borderRadius: 0.2,
                distance: 6,
                rotation: -53,
                strokeWidth: 5,
                sides: 7,
                size: 425,
                calcOpacity: ['interpolate', 'flip'],
                calcStrokeWidth: ['interpolate'],
                colorInterPolator: 'interpolateCool',
            },
        },
        {
            src: require('@/assets/img/icon-6.png'),
            shape: 'polygon',
            parameters: {
                amount: 16,
                distance: 16,
                rotation: 900,
                strokeWidth: 6,
                sides: 3,
                size: 430,
                colorInterPolator: 'interpolateRdBu',
            },
        },
        {
            src: require('@/assets/img/icon-7.png'),
            shape: 'rect',
            parameters: {
                amount: 12,
                distance: 30,
                strokeWidth: 10,
                width: 410,
                height: 410,
                borderRadius: {
                    tl: 1, tr: 1, bl: 0, br: 1,
                },
                borderRadiusIsLocked: false,
                calcStrokeWidth: ['interpolate'],
                colorInterPolator: 'interpolateCividis',
            },
        },
        {
            src: require('@/assets/img/icon-8.png'),
            shape: 'polygon',
            parameters: {
                amount: 178,
                distance: -7.3,
                rotation: 54,
                strokeWidth: 11.5,
                sides: 3,
                size: 122,
                calcOpacity: ['interpolate'],
                colorInterPolator: 'interpolateOranges',
            },
        },
        {
            src: require('@/assets/img/icon-9.png'),
            shape: 'circle',
            parameters: {
                amount: 272,
                distance: -4.2,
                rotation: -126,
                strokeWidth: 6.5,
                radiusX: 220,
                radiusY: 1,
                radiusIsLocked: false,
                calcOpacity: ['interpolate'],
                colorInterPolator: 'interpolateViridis',
            },
        },
        {
            src: require('@/assets/img/icon-10.png'),
            shape: 'rect',
            parameters: {
                borderRadius: {
                    tl: 0, tr: 0, bl: 0, br: 0,
                },
                amount: 84,
                distance: -6.5,
                strokeWidth: 30,
                rotation: 90,
                width: 15,
                height: 15,
                calcOpacity: ['interpolate'],
                colorInterPolator: 'interpolatePuRd',
            },
        },
        {
            src: require('@/assets/img/icon-11.png'),
            shape: 'polygon',
            parameters: {
                borderRadius: 0.8,
                amount: 16,
                distance: 24,
                rotation: 110,
                stroke: false,
                size: 450,
                sides: 6,
                calcOpacity: ['interpolate', 'flip'],
                colorInterPolator: 'interpolateYlOrRd',
                flipColorInterpolator: true,
            },
        },
        {
            src: require('@/assets/img/icon-12.png'),
            shape: 'rect',
            parameters: {
                borderRadiusIsLocked: false,
                borderRadius: {
                    tl: 0, tr: 1, bl: 0, br: 1,
                },
                amount: 16,
                distance: 24,
                strokeWidth: 4.5,
                width: 350,
                height: 350,
                flipColorInterpolator: true,
                colorInterPolator: 'interpolateSinebow',
            },
        },
        {
            src: require('@/assets/img/icon-13.png'),
            shape: 'rect',
            parameters: {
                borderRadiusIsLocked: false,
                borderRadius: {
                    tl: 0.5, tr: 0.5, bl: 0.5, br: 0.5,
                },
                amount: 25,
                rotation: 90,
                distance: 10,
                strokeWidth: 20,
                width: 250,
                height: 350,
                flipColorInterpolator: true,
                sizeIsLocked: false,
                calcOpacity: ['interpolate', 'flip'],
                calcStrokeWidth: ['interpolate', 'flip'],
                colorInterPolator: 'interpolateYlOrBr',
            },
        },
        {
            src: require('@/assets/img/icon-14.png'),
            shape: 'polygon',
            parameters: {
                borderRadius: 0.5,
                amount: 32,
                distance: 9,
                rotation: 120,
                strokeWidth: 12,
                size: 512,
                sides: 3,
                cy: -20,
                calcOpacity: ['interpolate'],
                calcStrokeWidth: ['interpolate', 'flip'],
                colorInterPolator: 'interpolateYlGnBu',
            },
        },
        {
            src: require('@/assets/img/icon-15.png'),
            shape: 'polygon',
            parameters: {
                borderRadius: 1,
                amount: 100,
                distance: 2,
                rotation: -175,
                strokeWidth: 5,
                size: 450,
                sides: 7,
                calcOpacity: ['interpolate'],
                calcStrokeWidth: ['interpolate', 'flip'],
                colorInterPolator: 'interpolateGreys',
            },
        },
        {
            src: require('@/assets/img/icon-16.png'),
            shape: 'circle',
            parameters: {
                amount: 20,
                distance: 0.5,
                rotation: 45,
                strokeWidth: 12,
                radiusX: 425,
                radiusY: 145,
                radiusIsLocked: false,
                calcOpacity: ['interpolate'],
                calcStrokeWidth: ['interpolate'],
                colorInterPolator: 'interpolateRdBu',
                flipColorInterpolator: true,
            },
        },
        {
            src: require('@/assets/img/icon-17.png'),
            shape: 'circle',
            parameters: {
                amount: 122,
                distance: 0,
                rotation: -90,
                strokeWidth: 1,
                radiusX: 400,
                radiusY: 175,
                radiusIsLocked: false,
                calcOpacity: ['interpolate'],
                colorInterPolator: 'interpolateMagma',
                flipColorInterpolator: true,
            },
        },
        {
            src: require('@/assets/img/icon-18.png'),
            shape: 'polygon',
            parameters: {
                borderRadius: 0.05,
                amount: 80,
                distance: 0,
                rotation: 145,
                strokeWidth: 30,
                size: 400,
                sides: 3,
                calcOpacity: ['interpolate', 'flip'],
                calcStrokeWidth: ['interpolate', 'flip'],
                flipColorInterpolator: true,
                colorInterPolator: 'interpolateRdYlBu',
            },
        },
        {
            src: require('@/assets/img/icon-19.png'),
            shape: 'rect',
            parameters: {
                borderRadius: {
                    tl: 0.8, tr: 0.8, bl: 0.8, br: 0.8,
                },
                amount: 60,
                rotation: 90,
                distance: 0.1,
                strokeWidth: 3,
                width: 150,
                height: 425,
                flipColorInterpolator: true,
                sizeIsLocked: false,
                calcOpacity: ['interpolate', 'flip'],
                calcStrokeWidth: ['interpolate', 'flip'],
                colorInterPolator: 'interpolateTurbo',
            },
        },
        {
            src: require('@/assets/img/icon-20.png'),
            shape: 'rect',
            parameters: {
                borderRadius: {
                    tl: 0.5, tr: 0.5, bl: 0.5, br: 0.5,
                },
                amount: 710,
                rotation: 180,
                distance: 0.5,
                strokeWidth: 1,
                width: 350,
                height: 350,
                sizeIsLocked: false,
                calcOpacity: ['interpolate', 'flip'],
                calcStrokeWidth: ['interpolate'],
                colorInterPolator: 'interpolateWarm',
            },
        },
        /* eslint-enable global-require */
    ],
    format: {
        float: '.2~f',
        standard: '.4~s',
        currency: '$.3~s',
        percent: '.1~%',
    },
    colorInterPolators: [
        { name: 'interpolateBrBG', fn: interpolateBrBG },
        { name: 'interpolatePRGn', fn: interpolatePRGn },
        { name: 'interpolatePiYG', fn: interpolatePiYG },
        { name: 'interpolatePuOr', fn: interpolatePuOr },
        { name: 'interpolateRdBu', fn: interpolateRdBu },
        { name: 'interpolateRdGy', fn: interpolateRdGy },
        { name: 'interpolateRdYlBu', fn: interpolateRdYlBu },
        { name: 'interpolateRdYlGn', fn: interpolateRdYlGn },
        { name: 'interpolateSpectral', fn: interpolateSpectral },
        { name: 'interpolateBlues', fn: interpolateBlues },
        { name: 'interpolateGreens', fn: interpolateGreens },
        { name: 'interpolateGreys', fn: interpolateGreys },
        { name: 'interpolateOranges', fn: interpolateOranges },
        { name: 'interpolatePurples', fn: interpolatePurples },
        { name: 'interpolateReds', fn: interpolateReds },
        { name: 'interpolateTurbo', fn: interpolateTurbo },
        { name: 'interpolateViridis', fn: interpolateViridis },
        { name: 'interpolateInferno', fn: interpolateInferno },
        { name: 'interpolateMagma', fn: interpolateMagma },
        { name: 'interpolatePlasma', fn: interpolatePlasma },
        { name: 'interpolateCividis', fn: interpolateCividis },
        { name: 'interpolateWarm', fn: interpolateWarm },
        { name: 'interpolateCool', fn: interpolateCool },
        { name: 'interpolateCubehelixDefault', fn: interpolateCubehelixDefault },
        { name: 'interpolateBuGn', fn: interpolateBuGn },
        { name: 'interpolateBuPu', fn: interpolateBuPu },
        { name: 'interpolateGnBu', fn: interpolateGnBu },
        { name: 'interpolateOrRd', fn: interpolateOrRd },
        { name: 'interpolatePuBuGn', fn: interpolatePuBuGn },
        { name: 'interpolatePuBu', fn: interpolatePuBu },
        { name: 'interpolatePuRd', fn: interpolatePuRd },
        { name: 'interpolateRdPu', fn: interpolateRdPu },
        { name: 'interpolateYlGnBu', fn: interpolateYlGnBu },
        { name: 'interpolateYlGn', fn: interpolateYlGn },
        { name: 'interpolateYlOrBr', fn: interpolateYlOrBr },
        { name: 'interpolateYlOrRd', fn: interpolateYlOrRd },
        { name: 'interpolateRainbow', fn: interpolateRainbow },
        { name: 'interpolateSinebow', fn: interpolateSinebow },
    ],
};
