on: push
name: 🚀 Deploy website on push
jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v3

            - name: 💻 Use Node.js 16
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: 🔨 Build Project
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  VITE_APP_EMAIL: ${{ vars.VITE_APP_EMAIL }}
                  VITE_APP_NAME: ${{ vars.VITE_APP_NAME }}
                  VITE_APP_DESCRIPTION: ${{ vars.VITE_APP_DESCRIPTION }}
                  VITE_APP_DESCRIPTION_EXTENDED: ${{ vars.VITE_APP_DESCRIPTION_EXTENDED }}
              run: |
                  npm install
                  npm run build

            # - name: 📋 Run unit tests
            #   run: npm run test:unit

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  local-dir: ./dist/
                  server-dir: /geometrica.niekes.com/
                  server: ${{ secrets.NIEKES_HOST }}
                  username: ${{ secrets.NIEKES_USERNAME }}
                  password: ${{ secrets.NIEKES_PASSWORD }}
